import Head from "next/head";
import Image from "next/image";

export default function Home() {
	return (
		<>
			<section>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<div>
					<div className="navbar">
						<nav id="navegador">
							<div>
								<a href="index.html"></a>
							</div>
							<input type="checkbox" id="check"></input>
							<label className="bar-btn">
								<i className="fa-solid fa-bars"></i>
							</label>
							<ul className="nav-menu">
								<li>
									<a className="active" href="index.html">
										INICIO
									</a>
								</li>
								<li>
									<a href="aboutus.html">DESCUBREME</a>
								</li>

								<li>
									<a href="https://open.spotify.com/show/02uUmZEKDXD5L61AYFkohu?si=6371898db55043d0">
										PODCAST
									</a>
								</li>
								<li>
									<a href="mentorias.html">MENTORIAS</a>
								</li>
							</ul>
						</nav>

						<div id="divinicio"></div>
					</div>
				</div>

				<section id="uppercontainer">
					<section id="hero">
						<h2>
							Escuela <span className="color">Red Pill</span>
						</h2>
						<h3>by Juan lopez</h3>
						<div id="secondline">
							<div id="text"></div>
							<div id="cursor"></div>
						</div>
					</section>
				</section>

				<section id="linktree">
					<div className="container">
						<div className="head__section">
							<p>Psicólogo profesional y freelancer.</p>
							<p>Descubrelo</p>
							<div className="arrow bounce"></div>

							<ul className="social_header">
								<a href="https://t.me/escuelaredpill">
									{" "}
									<li></li>
								</a>
								<a href="https://www.instagram.com/escuelaredpill/"> </a>
								<a href="https://www.tiktok.com/@escuelaredpill?lang=en">
									{" "}
									<li></li>
								</a>
							</ul>
						</div>
						<div className="social__links">
							<ul id="item">
								<li className="patreon">
									<a href="mentorias.html">
										<span>
											<p>MENTORIAS Y CONSULTAS</p>
										</span>
									</a>
								</li>
								<li className="youtube">
									<a href="https://www.youtube.com/channel/UCKsfHuc4kXMvUuiHRX3jdwA">
										<span>
											<p>YOUTUBE</p>
										</span>
									</a>
								</li>
								<li className="spotify">
									<a href="">
										<span>
											<p>SPOTIFY</p>
										</span>
									</a>
								</li>
								<li className="Article">
									<a href="https://blog.drjuanlopez.com">
										<i className="fa-solid fa-newspaper"></i>
										<span>
											<p>ARTICULOS</p>
										</span>
									</a>
								</li>

								<li className="Team">
									<a href="aboutus.html">
										<span>
											<p>NOSOTROS</p>
										</span>
									</a>
								</li>
							</ul>
						</div>
					</div>
				</section>
				<section id="cards-1">
					<article>
						<div>
							<h1>REINVINDICACION MASCULINA</h1>
							<p>
								Forja tu masculinidad y descubre tu potencial más atractivo.
							</p>
						</div>
					</article>
					<article>
						<div>
							<h1>Aprende a sostener una relacion</h1>
							<p>
								Entiende los conceptos fundamentales para mantener una relación
								estable.
							</p>
						</div>
					</article>
					<article>
						<div>
							<h1>Recuperate de tu ex</h1>
							<p>
								Si la relación termino y sientes que te perdiste a ti mismo o
								quieres intentar recuperar la relación.
							</p>
						</div>
					</article>
				</section>
				<div className="man-container"></div>
				<section id="bottom">
					<form action="mentorias.html">
						<button type="submit">ADQUIERE TU MENTORIA</button>
					</form>
				</section>
			</section>

			<div className="ultimopodcast">
				<div className="testimonials3">
					<div className="tittle3">
						<h1>Ultimos Podcast</h1>
						<div className="border3"></div>
					</div>
					<div className="inner3">
						<div className="row3">
							<div className="col3">
								<div className="testimonial3"></div>
							</div>

							<div className="col3">
								<div className="testimonial3"></div>
							</div>

							<div className="col3">
								<div className="testimonial3"></div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div className="testimonials4">
				<div className="tittle4">
					<h1>Ultimos Videos</h1>
					<div className="border4"></div>
				</div>
				<div className="inner4">
					<div className="row4">
						<div className="col4">
							<div className="testimonial4">
								<iframe
									id="link"
									width="350"
									height="250"
									title="YouTube video player"
									allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
								></iframe>
							</div>
						</div>

						<div className="col4">
							<div className="testimonial4">
								<iframe
									id="link2"
									width="350"
									height="250"
									title="YouTube video player"
									allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
								></iframe>
							</div>
						</div>

						<div className="col4">
							<div className="testimonial4">
								<iframe
									id="link3"
									width="350"
									height="250"
									src=""
									title="YouTube video player"
									allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
								></iframe>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div className="testimonials5">
				<div className="tittle5">
					<h1>Ultimos Articulos</h1>
					<div className="border5"></div>
				</div>
				<div className="inner5">
					<div className="row5">
						<div className="col5">
							<a href="https://blogredpill.jetpage.site/blog/el-porqu-te-dejan-las-mujeres-la-betaizacion">
								<div className="testimonial5">
									<div className="imagen1"></div>
									<div className="name5">
										El porque TE DEJAN LAS MUJERES.. LA BETAIZACION.
									</div>

									<h4>6/5/2022</h4>
								</div>
							</a>
						</div>

						<div className="col5">
							<a href="https://blogredpill.jetpage.site/blog/pruebas-que-te-hacen-las-mujeres-shit-test">
								<div className="testimonial5">
									<div className="imagen2"></div>
								</div>
								<div className="name5">
									PRUEBAS que te hacen las MUJERES ..SHIT TEST
								</div>

								<h4>6/3/2022</h4>
							</a>
						</div>

						<div className="col5">
							<a href="https://blogredpill.jetpage.site/blog/la-verdad-de-las-mujeres-hipergamia">
								<div className="testimonial5">
									<div className="imagen3"></div>
									<div className="name5">
										LA VERDAD de las MUJERES.. HIPERGAMIA
									</div>

									<h4>6/1/2022</h4>
								</div>
							</a>
						</div>
					</div>
				</div>
			</div>

			<footer>
				<div className="footer-content">
					<h3>
						Escuela <span className="color">Red Pill</span>
					</h3>
					<p>
						Este proyecto esta dirigido a aquellos hombres que no entienden como
						relacionarse adecuadamente con el sexo femenino, se realizará una
						serie de videos sobre las claves para una relación estable.
					</p>
					<ul className="socials">
						<li>
							<a href="https://www.instagram.com/escuelaredpill/">
								<i className="fa-brands fa-instagram"></i>
							</a>
						</li>
						<li>
							<a href="juanjoc3@hotmail.com">
								<i className="fa-light fa-at"></i>
							</a>
						</li>
						<li>
							<a href="https://www.tiktok.com/@escuelaredpill?lang=en">
								<i className="fa-brands fa-tiktok"></i>
							</a>
						</li>
						<li>
							<a href="twitch.tv/juanlpzz">
								<i className="fa-brands fa-twitch"></i>
							</a>
						</li>
					</ul>

					<div className="footer-bottom">
						<div className="copyright">
							<p>
								Copyright ©{" "}
								<a href="https://github.com/NevercomeG">
									NevercomeG<i className="fa-brands fa-github"></i>
								</a>
							</p>
						</div>
						<nav className="footer-menu">
							<ul className="f-menu">
								<li>
									<a href="#navegador">
										<i className="fa-solid fa-arrow-up"></i>
									</a>
								</li>
							</ul>
						</nav>
					</div>
				</div>
			</footer>
		</>
	);
}
