import Head from "next/head";
import Image from "next/image";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
// import { faCoffee } from "@fortawesome/free-solid-svg-icons";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<div className="flex flex-1 justify-center items-center">
					<div className="wrapper">
						<div className="image-cropper ">
							<Image
								src="/assets/IMG13_8642.png"
								width={100}
								height={100}
								alt=""
							/>
						</div>
						<h3>Juan López</h3>
						<h2 className="user-name">
							<a href="https://www.instagram.com/lookmomnohands/">
								@escuelaredpill
							</a>
						</h2>

						<div className="links">
							<a href="#" className="link">
								Escuela Red Pill
							</a>
							<div className=" text-xs items-center justify-center flex flex-1 ">
								<p>Lorem ipsum dolor sit amet.</p>
							</div>

							<br />
							<a href="#" className="link">
								Consultas psicologias
							</a>
							<a href="#" className="link">
								Arma tu PC
							</a>
						</div>

						<div className="links">
							<a href="#" className="link">
								Escuela Red Pill
							</a>
							<a href="#" className="link">
								Consultas psicologias
							</a>
							<a href="#" className="link">
								Arma tu PC
							</a>
						</div>
						<div className="links">
							<ul className="socials">
								<li>
									<a href=""></a>
								</li>
								<li>
									<a href=""></a>
								</li>
								<li>
									<a href="">
										<i className="fa-brands fa-tiktok"></i>
									</a>
								</li>
								<li>
									<a href="">
										<i className="fa-brands fa-twitch"></i>
									</a>
								</li>
								<li>
									<a href="">
										<i className="fa-brands fa-github"></i>
									</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
